### ISSUE TITLE
newSpan not confirming type assertion (panic)

### ISSUE THREAD

**Issue by iheanyi** [lightstep/lightstep-tracer-go#182]
Is this intentional? This line specifically [here](https://github.com/lightstep/lightstep-tracer-go/blob/master/span.go#L50) should probably be `refCtx, ok` and if it's `!ok`, it should bail out. Unless there's a good reason for it panicking that I'm unaware of. I was burned by this today unexpectedly, so any insights would be great. Thank you!

**Comment by iredelmeier** [comment]
No reason that I am aware of. #183 should fix it.

**Comment by iheanyi** [comment]
Thank you for fixing this!
