### ISSUE TITLE
Wrong version trying to be pulled (0.16.0)

### ISSUE THREAD

**Issue by unmultimedio** [lightstep/lightstep-tracer-go#186]
Hi, Lightstep team

I was trying to build a Go project with a dependency defined in my `glide.yaml` as:

```
- package: github.com/lightstep/lightstep-tracer-go
  version: ^v0.15.6
```

but everytime I ran `glide --debug (install|update)` I kept on getting the error:

```
[INFO]    --> Fetching updates for github.com/lightstep/lightstep-tracer-go
[WARN]    Download failed.
[WARN]    Error updating github.com/lightstep/lightstep-tracer-go/lightstep_thrift: Unable to update repository: exit status 1
[DEBUG]    Output was: Your configuration specifies to merge with the ref 'refs/heads/v0.16.0'
from the remote, but no such ref was fetched.[DEBUG]    Package github.com/lightstep/lightstep-tracer-go imports github.com/lightstep/lightstep-tracer-go/thrift_0_9_2/lib/go/thrift
[DEBUG]    In vendor: github.com/lightstep/lightstep-tracer-go/thrift_0_9_2/lib/go/thrift
[DEBUG]    Marking github.com/lightstep/lightstep-tracer-go/thrift_0_9_2/lib/go/thrift to be scanned.
```

So I was trying to look where in my code I was referencing to that `0.16.0` version, and couldn't find it. More so, I see your most recent version atm is `0.15.6`, so I changed the dependency to _(Note the `^~`)_:

```
- package: github.com/lightstep/lightstep-tracer-go
  version: ~v0.15.6
```

And now it pulls the correct version. I think you might have released by mistake a `0.16.0` version and then deleted it?

**Comment by austinlparker** [comment]
Huh, I don't think we did, but I'll do some digging and get back to you.

**Comment by austinlparker** [comment]
It looks like we did have a non-released branch for 0.16.0 that was used in some internal configs, but it was deleted. Try `git fetch --prune` to remove it from your local?

**Comment by unmultimedio** [comment]
Thanks for the response @austinlparker, but no luck. After that `git fetch --prune` and even after deleting the dependency repo completely and doing `glide (install|update)` again, logs still says the same message as the first one I posted.

**Comment by unmultimedio** [comment]
Hi LS Team, any updates on this? Is version `0.16.x` coming anytime soon? Glide is insisting on that one when pulling `0.x.x` and as of now, I had to force only versions `0.15.x`

**Comment by austinlparker** [comment]
We're planning on having a new major release in the next few weeks most likely, but it'll have some breaking changes so you might be best off pinning at 0.15.x for now.

**Comment by kayousterhout** [comment]
Closing this since it's now out of date.
