### ISSUE TITLE
Bump version of dep semver to 3.5.1

### ISSUE THREAD

**Issue by parker-edwards** [lightstep/lightstep-tracer-go#188]
Semver version 3.5.1 adds support for additional Go versions. Services with version locks at 3.5.1 require a version bump to enable support for the LS Tracer.

**Comment by austinlparker** [comment]
I don't see a semver package in the direct or transitive dependencies file - could you clarify the problem here?

**Comment by iredelmeier** [comment]
@parker-edwards I'm also confused. Which package is the problem?
