### ISSUE TITLE
Add B3 header support 

### ISSUE THREAD

**Issue by chadbrad** [lightstep/lightstep-tracer-go#224]
Please add B3 header support :) 

Please see this doc for the problem statement and specifics: https://docs.google.com/document/d/1ukvnSoXkavcojlVXpCRzep8PS_guXly_NbbhHIDgbFY/edit

This is high priority task, we need this ASAP. Please note the spec also covers trace-context and envoy support, but those are lower priority and captured in separate git issues. 

CC @tedsuo

**Comment by ledor473** [comment]
@codeboten is there any particular reason why `Propagator` in `options.go` is a String and directly the [underlying structure you're converting the String to](https://github.com/lightstep/lightstep-tracer-go/pull/227/files#diff-46db78603208f38452c0333bec12ab2cR143-R153)?

It makes it pretty hard to extend the capability of the Go tracer compared to the [Java](https://github.com/lightstep/lightstep-tracer-java-common/issues/56) and [NodeJS](https://github.com/lightstep/lightstep-tracer-javascript/commit/d46e32a97549decfbadf22b82e030ce4118d22b2#diff-04c6e90faac2675aa89e2176d2eec7d8R106) implementation.

The current implementation also doesn't allow to have multiple propagators (B3 + LS) at the same time to ease the migration from one to the other.

**Comment by codeboten** [comment]
@ledor473 thanks for the quick feedback! This was an oversight on my part and I created issue #238 to track the work to update this. I'll see about getting a PR reviewed today.

**Comment by ledor473** [comment]
That's awesome! Thanks @codeboten 👍

**Comment by codeboten** [comment]
Here's the PR https://github.com/lightstep/lightstep-tracer-go/pull/239
