### ISSUE TITLE
Add trace-context header support 

### ISSUE THREAD

**Issue by chadbrad** [lightstep/lightstep-tracer-go#225]
Please add trace-context header support

Please see this doc for the problem statement and specifics: https://docs.google.com/document/d/1ukvnSoXkavcojlVXpCRzep8PS_guXly_NbbhHIDgbFY/edit

**Comment by kayousterhout** [comment]
Closing this - we recommend getting trace-context header support by using OpenTelemetry with the Lightstep launchers: https://github.com/lightstep/otel-launcher-go
