### ISSUE TITLE
Allow `NewTracer` to return error.

### ISSUE THREAD

**Issue by bwplotka** [lightstep/lightstep-tracer-go#226]
Hi :wave: 

Any particular reason why there is no proper error handling for `NewTracer` constructor? 

I would vote for extending return arg and add `err` (: 

https://github.com/lightstep/lightstep-tracer-go/blob/HEAD/tracer.go#L88

**Comment by jmacd** [comment]
This will require a major version bump.  We could rename the existing method `MustNewTracer()` and panic instead of error. I'd prefer to just add a new method like `NewTracerChecked()`, given that we're putting a lot of effort into the OTel libraries, at this point.

**Comment by bwplotka** [comment]
Oh yea, it definitely can be a separate constructor. Happy to contribute.

**Comment by jmacd** [comment]
We would be glad to accept a pull request for this. Thanks!
