### ISSUE TITLE
Build failure for macOS/arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by alexfjw** [lightstep/lightstep-tracer-go#281]
The project fails to build on Apple Silicon devices due to usage of gopsutil/v2.
See https://github.com/shirou/gopsutil/issues/1000. 

This issue is prevalent in many opensource go libraries and can be resolved by migrating to gopsutil/v3.
For example, https://github.com/kubernetes/minikube/pull/10115

**Comment by alexfjw** [comment]
I've created a PR for this, hope someone can take a look.
https://github.com/lightstep/lightstep-tracer-go/pull/280

**Comment by whopper** [comment]
👍 +1 on getting this merged in!

**Comment by codeboten** [comment]
Fixed with #280
