### ISSUE TITLE
Cut new release with gopsutil bump

### ISSUE THREAD

**Issue by aneeshusa** [lightstep/lightstep-tracer-go#290]
Hello! We use this package widely at my work where we are in the middle of upgrading to M1 Macs. I noticed https://github.com/lightstep/lightstep-tracer-go/commit/32244bdae70ddb08f779cad6ba75a264780855e7 was recently merged to update gopsutil to fix an issue on M1.

Is there any chance you could cut a new release with this change?
cc @codeboten who looks to have cut most of the recent releases and already updated the changelog: https://github.com/lightstep/lightstep-tracer-go/commit/1770a5da4bceffbde69cd3679417bb127171135c

**Comment by codeboten** [comment]
hi @aneeshusa! I'll be looking at making a release next week.

**Comment by codeboten** [comment]
This has been completed: https://github.com/lightstep/lightstep-tracer-go/releases/tag/v0.26.0

**Comment by aneeshusa** [comment]
Thank you @codeboten - saw you went ahead and removed the gopsutil dependency altogether! Have been rolling out the new lighstep-tracer-go version internally and it's working well.
