### ISSUE TITLE
limit number of log events

### ISSUE THREAD

**Issue by RaduBerinde** [lightstep/lightstep-tracer-go#46]
We had an issue where a bug was causing endless retries and the memory inside basictracer grew indefinitely. It would be great if there was an option to only keep the last `X` log events inside a span.

Assuming we implement this functionality in basictracer, would it be ok with lightstep to pass along that option? (similar to how we pass `DropSpanLogs`)

**Comment by bensigelman** [comment]
@RaduBerinde 

> Assuming we implement this functionality in basictracer, would it be ok with lightstep to pass along that option? (similar to how we pass DropSpanLogs)

Yes. Thanks.
