### ISSUE TITLE
collectorpb no longer builds due to breaking change in grpc

### ISSUE THREAD

**Issue by peterbourgon** [lightstep/lightstep-tracer-go#57]
```
ugh ~/src/github.com/lightstep/lightstep-tracer-go (master) git rev-parse --short HEAD
91ae78c
ugh ~/src/github.com/lightstep/lightstep-tracer-go (master) go build ./...
# github.com/lightstep/lightstep-tracer-go/collectorpb
collectorpb/collector.pb.go:631: undefined: grpc.SupportPackageIsVersion3
```

**Comment by djspoons** [comment]
I vendored a (working) version of gRPC in https://github.com/lightstep/lightstep-tracer-go/pull/55

Let me know if that doesn't help

**Comment by peterbourgon** [comment]
@djspoons [Libraries cannot vendor their deps](http://peter.bourgon.org/go-best-practices-2016/#dependency-management), so no, this doesn't help. Unfortunately.

**Comment by djspoons** [comment]
For the record, no gGPC types escape through the public interface of lightstep-tracer-go.

I will take a closer look in the morning.

**Comment by peterbourgon** [comment]
If it helps, you can check out the build failures I'm (still) getting over at https://github.com/go-kit/kit/pull/387

**Comment by peterbourgon** [comment]
Thanks, that almost did it :) Can you please update your vendored copy of x/net/context? The currently vendored copy uses alias syntax `=>` in Go 1.8, which has been removed and no longer compiles on the current tip.

**Comment by jmacd** [comment]
We this this addresses the issue:
https://github.com/lightstep/lightstep-tracer-go/pull/61

**Comment by tedsuo** [comment]
I am assuming this issue is resolved, feel free to reopen this issue or start a new one if there is further work to be done.
