### ISSUE TITLE
Inaccurate UI for child span

### ISSUE THREAD

**Issue by meirf** [lightstep/lightstep-tracer-go#78]
**Background**
I have a java server that is making an RPC call to a go server. The java rpc client and go rpc server are instrumented with lightstep. Everything about the trace looks normal except for where in the lightstep UI, the go rpc server span is placed.

The java span has ts 1493929521325 which is right before the request is sent to the go server. The go rpc server has 2 timestamps: 1493929521326 is when it received the request and started the span, 1493929521336 is after it responded and finished the span.

**Problem**
I would expect the UI to have the go span horizontally to the immediate right of the java span. Instead, it is far to the right.

The only possible cause I can think of is an incompatibility between v0.10.1 which java code is using and v0.9.1 which go is using. Is this a possibility? Do you have any thoughts on a possible cause?

The go code is essentially:
```
import (
    lightstep "github.com/lightstep/lightstep-tracer-go"
    opentracing "github.com/opentracing/opentracing-go"
)

tracer := lightstep.NewTracer(lightstep.Options{
    AccessToken: ls.AccessToken,
    Collector:   lightstep.Endpoint{ls.Host, ls.Port, true},
    Tags:        map[string]interface{}{lightstep.ComponentNameKey: component},
})

spanContext, err := tracer.Extract(opentracing.TextMap, opentracing.TextMapCarrier(req.GetLightstepData()))
span = tracer.StartSpan(
    endpoint,
    opentracing.ChildOf(spanContext))
}

// handle the request

span.Finish()
```

I am using these libraries:
github.com/opentracing/opentracing-go at 6edb48674bd9467b8e91fda004f2bd7202d60ce4
github.com/lightstep/lightstep-tracer-go at 3f04c904839c54177e85df579d910718b09c42a3

![screen shot 2017-05-04 at 11 27 35 pm](https://cloud.githubusercontent.com/assets/2043305/25733031/657edd4c-3123-11e7-893f-7c50e6f4c4b3.png)

**Comment by tedsuo** [comment]
Hi @meirf. This sounds like the clock correction code in java may be perturbing the span. 

Do you mind going to the  help center (via the doc's link in the top right nav menu in LightStep) and submit a request? That way we can communicate directly and get this resolved.

Thanks,
- Ted

**Comment by meirf** [comment]
Hey Ted,

We have instrumentation in java and go. I've confirmed that of the four permutations, only java->go has this problem.

It turns out java->go isn't a real concern for us.

I have to prioritize real concerns so unfortunately I don't have the bandwidth to communicate further on this right now :(

Meir

**Comment by tedsuo** [comment]
Ok thanks! We're aware of this issue - basically some code that helps with bad clocks on android can sometimes mildly mess with good clocks on the server.
