### ISSUE TITLE
API for cleaning up a tracer

### ISSUE THREAD

**Issue by RaduBerinde** [lightstep/lightstep-tracer-go#82]
In CockroachDB, we want to be able to start and stop using Lighstep, or change the Lightstep token (and potentially the collector address) without restarting. We can easily create a new tracer when the settings change; however, there is no API to clean up the background task of the previous tracer.

I know this is not part of the opentracing interface, so it would have to be a `Stop(opentracing.Tracer)` function that downcasts to the internal type.

**Comment by djspoons** [comment]
@jmacd @tedsuo would the two of you take a look at this? Thanks
